"""Add document content and filetype

Revision ID: 791d42f946f9
Revises: 8516e48bcf55
Create Date: 2025-06-06 08:39:36.067507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791d42f946f9'
down_revision: Union[str, None] = '8516e48bcf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filetype', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'filetype')
    # ### end Alembic commands ###
